server:
  port: 9090
spring:
  application:
    name: broker
#-------- CLOUD CONFIGS, RABBITMQ --------------
  cloud:
    function:
      definition: accountDetails;bankTransactionDetails
    stream:
      bindings:
        accountDetails-in-0:
          destination: send-communication
          group: ${spring.application.name}
          
        bankTransactionDetails-in-0:
          destination: bank-transaction-topic
          group: ${spring.application.name}
          
        accountDetails-out-0:
          destination: accounts-details-topic


  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s
#-------- ACTUATOR & OBSERVABILITY CONFIGS --------------
management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

  tracing:
    sampling:
      probability: 1.0


